version: "3"
services:
    proxy:
        image: okue/chat-app-proxy
        ports:
            - "8081:8081"
        links:
            - server:server_dev

    redis:
        image: redis
        ports:
            - "6379:6379"
        command: redis-server

    server:
        image: okue/chat-app-server
        volumes:
            - ./server:/app
        ports:
            - "8000:8000" # http
            - "6565:6565" # grpc
        links:
            - redis:redis
        environment:
            - REDIS_HOST=redis
